Repository swiftlang/swift-evolution, pull requests merged in 2023-02, with the labels that each got.

#1938 Update the "Swift" evolution proposal template.
  proposal-templates/0000-swift-template.md
Labels: evolution process

#1824 Add proposal for `AsyncStream` convenience factories
  proposals/0388-async-stream-factory.md
Labels: core team: has implementation

#1925 Add proposal for package registry publish
  proposals/0391-package-registry-publish.md
Labels: swiftpm
