Repository swiftlang/swift-evolution, pull requests merged in 2024-04, with the labels that each got.

#2382 Add upcoming feature flag to SE-0412 to match inclusion in compiler
  proposals/0412-strict-concurrency-for-global-variables.md
Labels: LSG

#2387 [SE-317] Fix typo
  proposals/0317-async-let.md
Labels: editorial, LSG

#2381 Add upcoming feature flag to SE-0352 to match inclusion in compiler
  proposals/0352-implicit-open-existentials.md
Labels: editorial, LSG

#2325 Proposal to introduce borrowing switch for noncopyable types
  proposals/0432-noncopyable-switch.md
Labels: LSG

#2385 Revise SE-0423 based on review feedback.
  proposals/0423-dynamic-actor-isolation.md
Labels: LSG

#2308 Synchronous Mutual Exclusion Lock
  proposals/0433-mutex.md
Labels: LSG

#2372 Add a proposal to improve usability of global-actor-isolated types.
  proposals/0434-global-actor-isolated-types-usability.md
Labels: LSG

#2401 Fix Typo for `0433-mutex.md` file
  proposals/0433-mutex.md
Labels: editorial, LSG

#2407 Normalize SE-0433 Review header field
  proposals/0433-mutex.md
Labels: editorial, LSG

#2411 Normalize fields for SE-0255
  proposals/0255-omit-return.md
Labels: editorial

#2392 Proposal: [SwiftPM] Swift Language Version Per Target
  proposals/0435-swiftpm-per-target-swift-language-version-setting.md
Labels: swiftpm, LSG
