Repository swiftlang/swift-evolution, pull requests merged in 2024-05, with the labels that each got.

#2429 Revise SE-0431 to remove the `@Sendable` implication.
  proposals/0431-isolated-any-functions.md
Labels: content change, LSG

#2408 Add "Objective-C Implementations in Swift" proposal
  proposals/0436-objc-implementation.md
Labels: LSG

#2445 Amend @retroactive proposal to allow same-package conformances
  proposals/0364-retroactive-conformance-warning.md
Labels: content change

#2389 SE-0400: State limitations
  proposals/0400-init-accessors.md
Labels: content change, LSG

#2420 [SE-0438] Metatype Keypaths
  proposals/0438-metatype-keypath.md
Labels: LSG

#2471 Fix syntax highlighting in SE-0438
  proposals/0438-metatype-keypath.md
Labels: formatting
