Repository swiftlang/swift-evolution, pull requests merged in 2024-11, with the labels that each got.

#2553 Proposal: Integer Generic Parameters
  proposals/ABCD-integer-generic-parameters.md
Labels: LSG

#2611 Metadata fixes for SE-0452
  proposals/0452-integer-generic-parameters.md
Labels: editorial

#2602 SE0450: Mention about `swift test`
  proposals/0450-swiftpm-package-traits.md
Labels: editorial, PSG

#2614 Remove upcoming feature flag from SE-0452
  proposals/0452-integer-generic-parameters.md
Labels: content change, LSG

#2587 Proposal: Vector
  proposals/0453-vector.md
Labels: standard library addition, LSG
