Repository swiftlang/swift-evolution, pull requests merged in 2025-04, with the labels that each got.

#2697 [Pitch] `yielding` coroutine accessors
  proposals/0474-yielding-accessors.md
Labels: LSG

#2726 [Observation] Proposal to add a transactional observation of values
  proposals/0475-observed.md
Labels: LSG

#2740 [ST-0010] Add ConditionTrait.evaluate()
  proposals/testing/0010-evaluate-condition.md
Labels: workgroup: ready, swift-testing

#2768 Add `@abi` proposal
  proposals/0476-abi-attr.md
Labels: LSG

#2789 [ST-0008] Add missing conformances to `CustomStringConvertible` and `Equatable`
  proposals/testing/0008-exit-tests.md
Labels: content change, swift-testing

#2777 Add a proposal for specifying default actor isolation per-file using a type alias.
  proposals/0478-default-isolation-typealias.md
Labels: LSG

#2675 [SE-NNNN] Method and Initializer Key Paths
  proposals/0479-method-and-initializer-keypaths.md
Labels: LSG

#2761 Warning Control Settings for SwiftPM
  proposals/0480-swiftpm-warning-control.md
Labels: LSG, ESG

#2816 Update state of ST-0010 and link to acceptance
  proposals/testing/0010-evaluate-condition.md
Labels: editorial, TWG

#2771 Proposal to unban weak let bindings
  proposals/0481-weak-let.md
Labels: LSG
