Repository swiftlang/swift-evolution, pull requests merged in 2025-02, with the labels that each got.

#2684 Extend the SE-0458 review
  proposals/0458-strict-memory-safety.md
Labels: content change, LSG

#2690 [SE-0453] `InlineArray` proposal is accepted
  proposals/0453-vector.md
Labels: editorial, LSG

#2621 Add a prospective vision for improving the approachability of data-race safety.
  visions/approachable-concurrency.md
Labels: vision, LSG

#2572 Add a proposal to change the execution semantics of nonisolated async functions.
  proposals/0461-async-function-isolation.md
Labels: LSG

#2695 [SE-0456] post review updates
  proposals/0456-stdlib-span-properties.md
Labels: content change, LSG

#2705 Replace newlines with `<br/>` in Mermaid flowchart
  process.md
Labels: not evolution

#2706 [SE-0461] Fix not correct syntax in a function call
  proposals/0461-async-function-isolation.md
Labels: editorial, LSG

#2689 [SE-0458] Improvements to strict memory safety checking based on the ongoing review
  proposals/0458-strict-memory-safety.md
Labels: content change, LSG

#2710 Accept SE-0458
  proposals/0458-strict-memory-safety.md
Labels: LSG

#2694 Proposal: Import Objective-C completion handler parameters as `@Sendable`.
  proposals/0463-sendable-completion-handlers.md
Labels: LSG

#2712 Link SE-0463 to its review thread
  proposals/0463-sendable-completion-handlers.md
Labels: LSG

#2713 [SE-0463] Fix sendable-completion-handlers status
  proposals/0463-sendable-completion-handlers.md
Labels: editorial, LSG
