Repository swiftlang/swift-evolution, pull requests merged in 2025-03, with the labels that each got.

#2688 [DRAFT] Add UTF8Span proposal
  proposals/0464-utf8span-safe-utf8-processing.md
Labels: LSG

#2657 Nonescapable stdlib primitives
  proposals/NNNN-nonescapable-stdlib-primitives.md
Labels: LSG

#2667 Add a proposal for configuring default actor isolation per module.
  proposals/0466-control-default-actor-isolation.md
Labels: LSG

#2732 Replace two outdated links in 'process.md'
  process.md
Labels: evolution process, editorial

#2681 [Pitch] MutableSpan and MutableRawSpan
  proposals/0467-MutableSpan.md
Labels: LSG

#2729 Update the Swift evolution process documentation to incorporate Swift Testing
  process.md
Labels: evolution process, swift-testing

#2700 Proposal to add `Hashable` conformance to `Async(Throwing)Stream.Continuation`
  proposals/0468-async-stream-continuation-hashable-conformance.md
Labels: LSG

#2619 Swift Task Naming API
  proposals/0469-task-names.md
Labels: LSG

#2718 Proposal to add exit tests to Swift Testing
  proposals/testing/0008-exit-tests.md
Labels: workgroup: ready, swift-testing

#2719 Proposal to add attachments to Swift Testing
  proposals/testing/0009-attachments.md
Labels: workgroup: ready, swift-testing

#2748 Add Review Manager field to header of Swift Testing proposal template
  proposal-templates/0000-swift-testing-template.md
  proposals/testing/0008-exit-tests.md
Labels: evolution process, swift-testing

#2720 Global-actor isolated conformances
  proposals/0470-isolated-conformances.md
Labels: LSG

#2716 [Concurrency] isIsolatingCurrentContext - Improved Custom SerialExecutor isolation checking
  proposals/NNNN-SerialExecutor-isIsolated.md
  proposals/nnnn-is-isolated-flow.graffle
  proposals/nnnn-is-isolated-flow.png
Labels: LSG

#2698 Proposal: Task.startSynchronously
  proposals/0472-task-start-synchronously-on-caller-context.md
Labels: LSG

#2722 Proposal to add epoch properties to SuspendingClock and ContinuousClock
  proposals/0473-clock-epochs.md
Labels: LSG
