Repository swiftlang/swift-evolution, pull requests merged in 2025-01, with the labels that each got.

#2580 Add SwiftPM @testable build setting proposal
  proposals/0455-swiftpm-testable-build-setting.md
Labels: LSG

#2618 [SE-0454]: adopt mimalloc for Windows toolchain
  proposals/0454-memory-allocator.md
Labels: PSG

#2642 Fix typo (missing dot) in SE-0450 text
  proposals/0450-swiftpm-package-traits.md
Labels: editorial, PSG

#2644 Update 0414-region-based-isolation.md
  proposals/0414-region-based-isolation.md
Labels: editorial, LSG

#2620 [pitch] `Span`-providing properties in the standard library
  proposals/AAAA-stdlib-span-properties.md
Labels: LSG

#2659 [SE0456] fix typo
  proposals/0456-stdlib-span-properties.md
Labels: editorial, LSG

#2660 [SE-0431] Fix typo
  proposals/0431-isolated-any-functions.md
Labels: editorial, LSG

#2649 [SE-0392] Editorial fixes
  proposals/0392-custom-actor-executors.md
Labels: editorial, LSG

#2643 Update 0414-region-based-isolation.md
  proposals/0414-region-based-isolation.md
Labels: editorial, LSG

#2581 Prospective vision: Optional Strict Memory Safety for Swift
  visions/memory-safety.md
Labels: vision, LSG
