Repository swiftlang/swift-evolution, pull requests merged in 2025-05, with the labels that each got.

#2820 Change state of ST-0010 to Implemented
  proposals/testing/0010-evaluate-condition.md
Labels: editorial, TWG

#2825 [SE-0467] Binary Static Library Artifacts Proposal
  proposals/0467-swiftpm-static-library-binary-target-non-apple-platforms.md
Labels: workgroup: ready, PSG, ESG

#2829 SE-0443: Update proposal to reflect chosen diagnostic group name style
  proposals/0443-warning-control-flags.md
Labels: content change, LSG

#2837 Consistently format the 'Review:' header field of all Swift Testing proposals
  proposals/testing/0001-refactor-bug-inits.md
  proposals/testing/0002-json-abi.md
  proposals/testing/0003-make-serialized-trait-api.md
  proposals/testing/0004-constrain-the-granularity-of-test-time-limit-durations.md
  proposals/testing/0005-ranged-confirmations.md
  proposals/testing/0006-return-errors-from-expect-throws.md
  proposals/testing/0007-test-scoping-traits.md
  proposals/testing/0008-exit-tests.md
  proposals/testing/0009-attachments.md
  proposals/testing/0010-evaluate-condition.md
Labels: editorial, TWG

#2842 Add a review proposal announcement template for Swift Testing to process documentation
  process.md
Labels: evolution process, LSG, TWG

#2814 Allow Additional Arguments to `@dynamicMemberLookup` Subscripts
  proposals/0484-allow-additional-args-to-dynamicmemberlookup-subscripts.md
Labels: LSG

#2849 Accept SE-0481
  proposals/0481-weak-let.md
Labels: LSG

#2803 [Pitch] OutputSpan
  proposals/nnnn-outputspan.md
Labels: LSG

#2679 Pitch for extensible enums
  proposals/NNNN-extensible-enums.md
Labels: LSG
